### PR TITLE
added missing jquery-bridget dependency

### PR DESCRIPTION
**Pull request by rubencosta**
Hi, I've added the missing *jquery-bridget* dependency to *bower.json* .  Please review.

### CODE REVIEW

**Comment by passy** [comment]
@rubencosta This plugin doesn't directly depend on any of the APIs exposed by `bridget`. It only transitively depends on it, which is already managed by bower. Why do you want the explicit inclusion?

**Comment by rubencosta** [comment]
@passy Ok I understand, `jquery-bridget` Is under `masonry` devDependencies. I am not using `-p` flag on `bower install` and still, `bridget` is not being installed.
``````````````````````````````````````````````````
angular-masonry#0.11.0 public\vendor\angular-masonry
├── angular#1.3.16
├── imagesloaded#3.1.8
├── jquery#2.1.4
└── masonry#3.2.3

masonry#3.2.3 public\vendor\masonry
├── get-size#1.2.2
└── outlayer#1.3.0

imagesloaded#3.1.8 public\vendor\imagesloaded
├── eventEmitter#4.2.11
└── eventie#1.0.6

get-size#1.2.2 public\vendor\get-size
└── get-style-property#1.0.4

outlayer#1.3.0 public\vendor\outlayer
├── doc-ready#1.0.4
├── eventEmitter#4.2.11
├── eventie#1.0.6
├── get-size#1.2.2
├── get-style-property#1.0.4
└── matches-selector#1.0.3

eventie#1.0.6 public\vendor\eventie

doc-ready#1.0.4 public\vendor\doc-ready
└── eventie#1.0.6

eventEmitter#4.2.11 public\vendor\eventEmitter

angular#1.3.16 public\vendor\angular

jquery#2.1.4 public\vendor\jquery

matches-selector#1.0.3 public\vendor\matches-selector

get-style-property#1.0.4 public\vendor\get-style-property

``````````````````````````````````````````````````

**Comment by passy** [comment]
@rubencosta You're absolutely right. I think one of the dependencies must have changed that. Would you mind updating the commit message to the [guidelines](https://github.com/passy/angular-masonry#contributing)?

**Comment by passy** [comment]
:+1: Thanks again!

**Pull request merged**
