### PR TITLE
Update angualr version

### PR DESCRIPTION
**Pull request by tomoyuki28jp**
https://github.com/passy/angular-masonry/issues/121

### CODE REVIEW

**Comment by passy** [comment]
This is not really how I want to use the specifier. If it works with 1.4, that should be specified via caret. People who are on 1.3 can use previous releases. Do you want to update it? If so, please take a look at the contribution guidelines.

**Comment by tomoyuki28jp** [comment]
@passy Thanks for your reply

> please take a look at the contribution guidelines.

The contribution guidelines say `Only change files in src and don't bump any versions`. You are talking about commit message format?

**Comment by passy** [comment]
@tomoyuki28jp Yes, precisely.

**Comment by tagCincy** [comment]
@passy this really needs to be addressed;  Angular is already in beta for 1.5.

**Comment by passy** [comment]
@tagCincy Want to take over and create a new PR?

**Comment by tagCincy** [comment]
Like this? https://github.com/passy/angular-masonry/pull/118

**Comment by passy** [comment]
The "semver-correct" way would be to specify `^1.4.0`.

**Pull request closed without merging**
