### PR TITLE
impr: added new event for reloading full grid

### PR DESCRIPTION
**Pull request by JohnnyTheTank**
with this event, everyone can trigger a grid reload from other directives

### CODE REVIEW

**Comment by passy** [comment]
Thanks for the PR!

However, I want to keep the API surface for this as small as possible. Could you describe which usecase you need this for? Is the extra round-trip through this plugin really necessary? Can't you just directly call `.masonry()` on the element instead?

**Comment by JohnnyTheTank** [comment]
Thanks for your fast response.

I understand your concerns, and I'm not 100% sure whats the best way. I search for a way to trigger a reload from another angular directive. the (already existing) event ´masonry.reload´ don't work for me.

I'm developing an angularjs plugin system for displaying any data, named **apiNG** ([demo](http://johnnythetank.github.io/apiNG/#demo)) and currently I'm working on the default design ([apiNG-design-default](https://github.com/JohnnyTheTank/apiNG-design-default)) which is based on your masonry directive and I've got big problems with overlapping items. I'm searching for an elegant generic solution for this problem.

Do you have any idea?

**Comment by JohnnyTheTank** [comment]
I don't need it anymore. I found a way. I used a custom version of this directive https://github.com/bimal1331/angular-images-loaded and called `masonry.reload` when the loaded events fires

**Comment by duhaime** [comment]
In case others land here looking for ways to trigger reload events, I'm able to use jQuery to do: `$('*[masonry]').masonry();`, which produces the masonry layout anew.

**Pull request closed without merging**
