### PR TITLE
Bump the AngularJS version so the module can install angular 1.4

### PR DESCRIPTION
**Pull request by vrouet**
The tests do run with angular 1.4, so this should be painless.

### CODE REVIEW

**Comment by passy** [comment]
Thanks! Can you follow the commit guidelines please? https://github.com/passy/angular-masonry#contributing

**Comment by vrouet** [comment]
I've rewritten the commit message to match the format

**Comment by passy** [comment]
Perfect, thank you!

**Comment by vrouet** [comment]
Great :) Will you release that new version now?

**Comment by passy** [comment]
Done! :sake:

**Pull request merged**
